
imagenet_classes = ["tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray",
                        "stingray", "rooster", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco",
                        "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper",
                        "kite (bird of prey)", "bald eagle", "vulture", "great grey owl", "fire salamander",
                        "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog",
                        "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin",
                        "box turtle", "banded gecko", "green iguana", "Carolina anole",
                        "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard",
                        "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile",
                        "American alligator", "triceratops", "worm snake", "ring-necked snake",
                        "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake",
                        "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra",
                        "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake",
                        "sidewinder rattlesnake", "trilobite", "harvestman", "scorpion", "yellow garden spider",
                        "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider",
                        "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peafowl",
                        "quail", "partridge", "african grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet",
                        "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck",
                        "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby",
                        "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch",
                        "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab",
                        "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab",
                        "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron",
                        "great egret", "bittern bird", "crane bird", "limpkin", "common gallinule", "American coot",
                        "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher",
                        "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion",
                        "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel",
                        "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle",
                        "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound",
                        "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound",
                        "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound",
                        "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier",
                        "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier",
                        "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier",
                        "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier",
                        "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer",
                        "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier",
                        "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier",
                        "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever",
                        "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla",
                        "English Setter", "Irish Setter", "Gordon Setter", "Brittany dog", "Clumber Spaniel",
                        "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniel", "Sussex Spaniel",
                        "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael dog", "Malinois", "Briard",
                        "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie",
                        "Border Collie", "Bouvier des Flandres dog", "Rottweiler", "German Shepherd Dog", "Dobermann",
                        "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog",
                        "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff",
                        "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky",
                        "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland dog",
                        "Great Pyrenees dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "brussels griffon",
                        "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle",
                        "Standard Poodle", "Mexican hairless dog (xoloitzcuintli)", "grey wolf", "Alaskan tundra wolf",
                        "red wolf or maned wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox",
                        "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat",
                        "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger",
                        "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose",
                        "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle",
                        "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper",
                        "cricket insect", "stick insect", "cockroach", "praying mantis", "cicada", "leafhopper",
                        "lacewing", "dragonfly", "damselfly", "red admiral butterfly", "ringlet butterfly",
                        "monarch butterfly", "small white butterfly", "sulphur butterfly", "gossamer-winged butterfly",
                        "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit",
                        "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel horse",
                        "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison",
                        "ram (adult male sheep)", "bighorn sheep", "Alpine ibex", "hartebeest", "impala (antelope)",
                        "gazelle", "arabian camel", "llama", "weasel", "mink", "European polecat",
                        "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan",
                        "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque",
                        "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin",
                        "howler monkey", "titi monkey", "Geoffroy's spider monkey", "common squirrel monkey",
                        "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda",
                        "giant panda", "snoek fish", "eel", "silver salmon", "rock beauty fish", "clownfish",
                        "sturgeon", "gar fish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown",
                        "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance",
                        "amphibious vehicle", "analog clock", "apiary", "apron", "trash can", "assault rifle",
                        "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo",
                        "baluster / handrail", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel",
                        "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel",
                        "bathtub", "station wagon", "lighthouse", "beaker", "military hat (bearskin or shako)",
                        "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle", "bikini",
                        "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet",
                        "bookcase", "bookstore", "bottle cap", "hunting bow", "bow tie", "brass memorial plaque", "bra",
                        "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest",
                        "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe",
                        "can opener", "cardigan", "car mirror", "carousel", "tool kit", "cardboard box / carton",
                        "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran",
                        "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw",
                        "storage chest", "chiffonier", "bell or wind chime", "china cabinet", "Christmas stocking",
                        "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker",
                        "coffee mug", "coffeemaker", "spiral or coil", "combination lock", "computer keyboard",
                        "candy store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot",
                        "cowboy hat", "cradle", "construction crane", "crash helmet", "crate", "infant bed",
                        "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer",
                        "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table",
                        "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig",
                        "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar",
                        "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder",
                        "feather boa", "filing cabinet", "fireboat", "fire truck", "fire screen", "flagpole", "flute",
                        "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed",
                        "freight car", "French horn", "frying pan", "fur coat", "garbage truck",
                        "gas mask or respirator", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola",
                        "gong", "gown", "grand piano", "greenhouse", "radiator grille", "grocery store", "guillotine",
                        "hair clip", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer",
                        "handkerchief", "hard disk drive", "harmonica", "harp", "combine harvester", "hatchet",
                        "holster", "home theater", "honeycomb", "hook", "hoop skirt", "gymnastic horizontal bar",
                        "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep",
                        "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat",
                        "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "letter opener", "library",
                        "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion",
                        "music speaker", "loupe magnifying glass", "sawmill", "magnetic compass", "messenger bag",
                        "mailbox", "tights", "one-piece bathing suit", "manhole cover", "maraca", "marimba", "mask",
                        "matchstick", "maypole", "maze", "measuring cup", "medicine cabinet", "megalith", "microphone",
                        "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile",
                        "mitten", "mixing bowl", "mobile home", "ford model t", "modem", "monastery", "monitor",
                        "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net", "vespa",
                        "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "metal nail",
                        "neck brace", "necklace", "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina",
                        "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt", "bullock cart",
                        "oxygen mask", "product packet / packaging", "paddle", "paddle wheel", "padlock", "paintbrush",
                        "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench",
                        "parking meter", "railroad car", "patio", "payphone", "pedestal", "pencil case",
                        "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube",
                        "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball",
                        "pinwheel", "pirate ship", "drink pitcher", "block plane", "planetarium", "plastic bag",
                        "plate rack", "farm plow", "plunger", "Polaroid camera", "pole", "police van", "poncho",
                        "pool table", "soda bottle", "plant pot", "potter's wheel", "power drill", "prayer rug",
                        "printer", "prison", "missile", "projector", "hockey puck", "punching bag", "purse", "quill",
                        "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel",
                        "recreational vehicle", "fishing casting reel", "reflex camera", "refrigerator",
                        "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser",
                        "rugby ball", "ruler measuring stick", "sneaker", "safe", "safety pin", "salt shaker", "sandal",
                        "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard",
                        "CRT monitor", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store",
                        "shoji screen / room divider", "shopping basket", "shopping cart", "shovel", "shower cap",
                        "shower curtain", "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door",
                        "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock",
                        "solar thermal collector", "sombrero", "soup bowl", "keyboard space bar", "space heater",
                        "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight",
                        "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf",
                        "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa",
                        "submarine", "suit", "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge",
                        "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch", "syringe",
                        "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball",
                        "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof",
                        "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store",
                        "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod",
                        "triumphal arch", "trolleybus", "trombone", "hot tub", "turnstile", "typewriter keyboard",
                        "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vaulted or arched ceiling",
                        "velvet fabric", "vending machine", "vestment", "viaduct", "violin", "volleyball",
                        "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink",
                        "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle",
                        "hair wig", "window screen", "window shade", "Windsor tie", "wine bottle", "airplane wing",
                        "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "sailboat", "yurt", "website",
                        "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket", "menu",
                        "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "popsicle", "baguette",
                        "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage", "broccoli",
                        "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber",
                        "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith apple", "strawberry", "orange",
                        "lemon", "fig", "pineapple", "banana", "jackfruit", "cherimoya (custard apple)", "pomegranate",
                        "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito",
                        "red wine", "espresso", "tea cup", "eggnog", "mountain", "bubble", "cliff", "coral reef",
                        "geyser", "lakeshore", "promontory", "sandbar", "beach", "valley", "volcano", "baseball player",
                        "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn",
                        "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom",
                        "earth star fungus", "hen of the woods mushroom", "bolete", "corn cob", "toilet paper"]
imagenet_templates = [
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
]

fgvc_aircraft_classes = [
    '707-320', '727-200', '737-200', '737-300', '737-400', '737-500', '737-600', '737-700', '737-800', '737-900',
    '747-100', '747-200', '747-300', '747-400', '757-200', '757-300', '767-200', '767-300', '767-400', '777-200',
    '777-300', 'A300B4', 'A310', 'A318', 'A319', 'A320', 'A321', 'A330-200', 'A330-300', 'A340-200', 'A340-300', 
    'A340-500', 'A340-600', 'A380', 'ATR-42', 'ATR-72', 'An-12', 'BAE 146-200', 'BAE 146-300', 'BAE-125', 'Beechcraft 1900',
    'Boeing 717', 'C-130', 'C-47', 'CRJ-200', 'CRJ-700', 'CRJ-900', 'Cessna 172', 'Cessna 208', 'Cessna 525',
    'Cessna 560', 'Challenger 600', 'DC-10', 'DC-3', 'DC-6', 'DC-8', 'DC-9-30', 'DH-82', 'DHC-1', 'DHC-6', 'DHC-8-100',
    'DHC-8-300', 'DR-400', 'Dornier 328', 'E-170', 'E-190', 'E-195', 'EMB-120', 'ERJ 135', 'ERJ 145', 'Embraer Legacy 600',
    'Eurofighter Typhoon', 'F-16A/B', 'F/A-18', 'Falcon 2000', 'Falcon 900', 'Fokker 100', 'Fokker 50', 'Fokker 70',
    'Global Express', 'Gulfstream IV', 'Gulfstream V', 'Hawk T1', 'Il-76', 'L-1011', 'MD-11', 'MD-80', 'MD-87', 'MD-90',
    'Metroliner', 'Model B200', 'PA-28', 'SR-20', 'Saab 2000', 'Saab 340', 'Spitfire', 'Tornado', 'Tu-134', 'Tu-154',
    'Yak-42', 
]

fgvc_aircraft_templates = [
    'a photo of a {}, a type of aircraft.',
    'a photo of the {}, a type of aircraft.',
]


cub_classes = ['Black footed Albatross', 'Laysan Albatross', 'Sooty Albatross', 'Groove billed Ani', 'Crested Auklet', 
               'Least Auklet', 'Parakeet Auklet', 'Rhinoceros Auklet', 'Brewer Blackbird', 'Red winged Blackbird', 
               'Rusty Blackbird', 'Yellow headed Blackbird', 'Bobolink', 'Indigo Bunting', 'Lazuli Bunting', 'Painted Bunting',
               'Cardinal', 'Spotted Catbird', 'Gray Catbird', 'Yellow breasted Chat', 'Eastern Towhee', 'Chuck will Widow', 
               'Brandt Cormorant', 'Red faced Cormorant', 'Pelagic Cormorant', 'Bronzed Cowbird', 'Shiny Cowbird', 
               'Brown Creeper', 'American Crow', 'Fish Crow', 'Black billed Cuckoo', 'Mangrove Cuckoo', 'Yellow billed Cuckoo',
               'Gray crowned Rosy Finch', 'Purple Finch', 'Northern Flicker', 'Acadian Flycatcher', 'Great Crested Flycatcher',
               'Least Flycatcher', 'Olive sided Flycatcher', 'Scissor tailed Flycatcher', 'Vermilion Flycatcher',
               'Yellow bellied Flycatcher', 'Frigatebird', 'Northern Fulmar', 'Gadwall', 'American Goldfinch', 'European Goldfinch',
               'Boat tailed Grackle', 'Eared Grebe', 'Horned Grebe', 'Pied billed Grebe',
               'Western Grebe', 'Blue Grosbeak', 'Evening Grosbeak', 'Pine Grosbeak', 'Rose breasted Grosbeak', 'Pigeon Guillemot',
               'California Gull', 'Glaucous winged Gull', 'Heermann Gull', 'Herring Gull', 'Ivory Gull', 'Ring billed Gull',
               'Slaty backed Gull', 'Western Gull', 'Anna Hummingbird', 'Ruby throated Hummingbird', 'Rufous Hummingbird',
               'Green Violetear', 'Long tailed Jaeger', 'Pomarine Jaeger', 'Blue Jay', 'Florida Jay', 'Green Jay', 
               'Dark eyed Junco', 'Tropical Kingbird', 'Gray Kingbird', 'Belted Kingfisher', 'Green Kingfisher', 'Pied Kingfisher',
               'Ringed Kingfisher', 'White breasted Kingfisher', 'Red legged Kittiwake', 'Horned Lark', 'Pacific Loon', 'Mallard',
               'Western Meadowlark', 'Hooded Merganser', 'Red breasted Merganser', 'Mockingbird', 'Nighthawk', 'Clark Nutcracker',
               'White breasted Nuthatch', 'Baltimore Oriole', 'Hooded Oriole', 'Orchard Oriole', 'Scott Oriole', 'Ovenbird',
               'Brown Pelican', 'White Pelican', 'Western Wood Pewee', 'Sayornis', 'American Pipit', 'Whip poor Will',
               'Horned Puffin', 'Common Raven', 'White necked Raven', 'American Redstart', 'Geococcyx', 'Loggerhead Shrike',
              'Great Grey Shrike', 'Baird Sparrow', 'Black throated Sparrow', 'Brewer Sparrow', 'Chipping Sparrow',
               'Clay colored Sparrow', 'House Sparrow', 'Field Sparrow', 'Fox Sparrow', 'Grasshopper Sparrow', 'Harris Sparrow',
                'Henslow Sparrow', 'Le Conte Sparrow', 'Lincoln Sparrow', 'Nelson Sharp tailed Sparrow', 'Savannah Sparrow',
                'Seaside Sparrow', 'Song Sparrow', 'Tree Sparrow', 'Vesper Sparrow', 'White crowned Sparrow',
                'White throated Sparrow', 'Cape Glossy Starling', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Tree Swallow',
                'Scarlet Tanager', 'Summer Tanager', 'Artic Tern', 'Black Tern', 'Caspian Tern', 'Common Tern', 'Elegant Tern',
                'Forsters Tern', 'Least Tern', 'Green tailed Towhee', 'Brown Thrasher', 'Sage Thrasher', 'Black capped Vireo',
                'Blue headed Vireo', 'Philadelphia Vireo', 'Red eyed Vireo', 'Warbling Vireo', 'White eyed Vireo',
                'Yellow throated Vireo', 'Bay breasted Warbler', 'Black and white Warbler', 'Black throated Blue Warbler',
                'Blue winged Warbler', 'Canada Warbler', 'Cape May Warbler', 'Cerulean Warbler', 'Chestnut sided Warbler',
                'Golden winged Warbler', 'Hooded Warbler', 'Kentucky Warbler', 'Magnolia Warbler', 'Mourning Warbler',
                'Myrtle Warbler', 'Nashville Warbler', 'Orange crowned Warbler', 'Palm Warbler', 'Pine Warbler',
                'Prairie Warbler', 'Prothonotary Warbler', 'Swainson Warbler', 'Tennessee Warbler', 'Wilson Warbler',
                'Worm eating Warbler', 'Yellow Warbler', 'Northern Waterthrush', 'Louisiana Waterthrush', 'Bohemian Waxwing',
                'Cedar Waxwing', 'American Three toed Woodpecker', 'Pileated Woodpecker', 'Red bellied Woodpecker',
                'Red cockaded Woodpecker', 'Red headed Woodpecker', 'Downy Woodpecker', 'Bewick Wren', 'Cactus Wren',
                'Carolina Wren', 'House Wren', 'Marsh Wren', 'Rock Wren', 'Winter Wren', 'Common Yellowthroat']


cub_templates = [
    'a photo of a {}',
    # 'a photo of the {}, a type of bird.',
]



sun_classes = ['abbey', 'access road', 'airfield', 'airlock', 'airplane cabin', 'airport airport', 'airport entrance', 'airport terminal',
            'airport ticket counter', 'alcove', 'alley', 'amphitheater', 'amusement arcade', 'amusement park', 'anechoic chamber',
            'apartment building outdoor', 'apse indoor', 'apse outdoor', 'aquarium', 'aquatic theater', 'aqueduct', 'arch', 'archaelogical excavation',
            'archive', 'arena basketball', 'arena hockey', 'arena performance', 'armory', 'arrival gate outdoor', 'art gallery', 'art school', 
            'art studio', 'artists loft', 'assembly line', 'athletic field outdoor', 'atrium home', 'atrium public', 'attic', 'auditorium', 
            'auto factory', 'auto mechanics indoor', 'auto racing paddock', 'auto showroom', 'backstage', 'badlands', 'badminton court indoor', 
            'badminton court outdoor', 'baggage claim', 'bakery kitchen', 'bakery shop', 'balcony exterior', 'balcony interior', 'ball pit', 'ballroom', 
            'bamboo forest', 'bank indoor', 'bank outdoor', 'bank vault', 'banquet hall', 'baptistry indoor', 'baptistry outdoor', 'bar', 'barn', 
            'barndoor', 'baseball field', 'basement', 'basilica', 'basketball court indoor', 'basketball court outdoor', 'bathroom', 'batters box', 
            'batting cage indoor', 'batting cage outdoor', 'bayou', 'bazaar indoor', 'bazaar outdoor', 'beach', 'beach house', 'beauty salon', 
            'bedchamber', 'bedroom', 'beer garden', 'beer hall', 'bell foundry', 'berth', 'betting shop', 'bicycle racks', 'bindery', 
            'biology laboratory', 'bistro indoor', 'bistro outdoor', 'bleachers outdoor', 'boardwalk', 'boat deck', 'boathouse', 'bog', 'bookstore', 
            'booth indoor', 'botanical garden', 'bow window indoor', 'bow window outdoor', 'bowling alley', 'boxing ring', 'brewery indoor', 
            'brewery outdoor', 'brickyard outdoor', 'bridge', 'building complex', 'building facade', 'bullpen', 'bullring', 'burial chamber', 
            'bus depot outdoor', 'bus interior', 'bus shelter', 'bus station outdoor', 'butchers shop', 'butte', 'cabana', 'cabin outdoor', 'cafeteria', 
            'call center', 'campsite', 'campus', 'canal natural', 'canal urban', 'candy store', 'canteen', 'canyon', 'car interior backseat', 
            'car interior frontseat', 'caravansary', 'cardroom', 'cargo deck airplane', 'carport freestanding', 'carport outdoor', 'carrousel', 
            'casino indoor', 'casino outdoor', 'castle', 'catacomb', 'cathedral indoor', 'cathedral outdoor', 'catwalk', 'cavern indoor', 'cemetery', 
            'chalet', 'chaparral', 'chapel', 'checkout counter', 'cheese factory', 'chemical plant', 'chemistry lab', 'chicken coop indoor', 
            'chicken coop outdoor', 'chicken farm indoor', 'chicken farm outdoor', 'childs room', 'church indoor', 'church outdoor', 'circus tent indoor', 
            'circus tent outdoor', 'city', 'classroom', 'clean room', 'cliff', 'cloister indoor', 'cloister outdoor', 'closet', 'clothing store', 
            'coast', 'cockpit', 'coffee shop', 'computer room', 'conference center', 'conference hall', 'conference room', 'confessional', 
            'construction site', 'control room', 'control tower indoor', 'control tower outdoor', 'convenience store indoor', 'corn field', 'corral', 
            'corridor', 'cottage', 'cottage garden', 'courthouse', 'courtroom', 'courtyard', 'covered bridge exterior', 'crawl space', 'creek', 
            'crevasse', 'crosswalk', 'cubicle office', 'cybercafe', 'dacha', 'dairy indoor', 'dam', 'darkroom', 'day care center', 'delicatessen', 
            'dentists office', 'departure lounge', 'desert road', 'desert sand', 'desert vegetation', 'diner indoor', 'diner outdoor', 'dinette home', 
            'dinette vehicle', 'dining car', 'dining hall', 'dining room', 'dirt track', 'discotheque', 'dock', 'dolmen', 'donjon', 'doorway indoor', 
            'doorway outdoor', 'dorm room', 'downtown', 'drainage ditch', 'drill rig', 'driveway', 'driving range outdoor', 'drugstore', 'dry dock', 
            'dugout', 'earth fissure', 'editing room', 'electrical substation', 'elevator door', 'elevator freight elevator', 'elevator interior', 
            'elevator lobby', 'elevator shaft', 'embassy', 'engine room', 'escalator indoor', 'escalator outdoor', 'estuary', 'excavation', 
            'exhibition hall', 'factory indoor', 'factory outdoor', 'fairway', 'farm', 'fastfood restaurant', 'fence', 'ferryboat outdoor', 
            'field cultivated', 'field road', 'field wild', 'fire escape', 'fire station', 'firing range indoor', 'firing range outdoor', 'fish farm', 
            'fishpond', 'fjord', 'flea market indoor', 'flea market outdoor', 'flight of stairs natural', 'flight of stairs urban', 'flood', 
            'florist shop indoor', 'fly bridge', 'food court', 'football field', 'forest broadleaf', 'forest needleleaf', 'forest path', 'forest road', 
            'formal garden', 'fort', 'fortress', 'foundry indoor', 'foundry outdoor', 'fountain', 'freeway', 'funeral chapel', 'furnace room', 'galley', 
            'game room', 'gangplank', 'garage indoor', 'garage outdoor', 'garbage dump', 'gas station', 'gasworks', 'gatehouse', 'gazebo exterior', 
            'general store indoor', 'general store outdoor', 'geodesic dome indoor', 'geodesic dome outdoor', 'ghost town', 'gift shop', 'glacier', 
            'golf course', 'gorge', 'great hall', 'greenhouse indoor', 'greenhouse outdoor', 'grotto', 'guardhouse', 'gulch', 'gun deck indoor', 
            'gymnasium indoor', 'hacienda', 'hallway', 'hangar indoor', 'hangar outdoor', 'harbor', 'hayfield', 'heath', 'hedge maze', 'hedgerow', 
            'heliport', 'herb garden', 'highway', 'hill', 'home office', 'home theater', 'hoodoo', 'hospital', 'hospital room', 'hot spring', 
            'hot tub indoor', 'hot tub outdoor', 'hotel breakfast area', 'hotel outdoor', 'hotel room', 'house', 'hunting lodge indoor', 
            'hunting lodge outdoor', 'hut', 'ice floe', 'ice shelf', 'ice skating rink indoor', 'ice skating rink outdoor', 'iceberg', 'igloo', 
            'industrial area', 'industrial park', 'inn indoor', 'inn outdoor', 'irrigation ditch', 'islet', 'jacuzzi indoor', 'jacuzzi outdoor', 
            'jail cell', 'jail indoor', 'jail outdoor', 'japanese garden', 'jewelry shop', 'joss house', 'junk pile', 'junkyard', 'jury box', 'kasbah', 
            'kennel indoor', 'kennel outdoor', 'kindergarden classroom', 'kiosk indoor', 'kiosk outdoor', 'kitchen', 'kitchenette', 'lab classroom', 
            'labyrinth indoor', 'labyrinth outdoor', 'lagoon', 'lake artificial', 'lake natural', 'landfill', 'landing deck', 'laundromat', 'lawn', 
            'lean-to', 'lecture room', 'levee', 'library indoor', 'library outdoor', 'lido deck outdoor', 'lift bridge', 'lighthouse', 
            'limousine interior', 'liquor store indoor', 'liquor store outdoor', 'living room', 'loading dock', 'lobby', 'lock chamber', 'locker room', 
            'lookout station outdoor', 'machine shop', 'manhole', 'mansion', 'manufactured home', 'market indoor', 'market outdoor', 'marsh', 
            'martial arts gym', 'mastaba', 'mausoleum', 'medina', 'mesa', 'military hospital', 'military hut', 'mine', 'mineshaft', 
            'mini golf course outdoor', 'mission', 'moat dry', 'moat water', 'mobile home', 'monastery outdoor', 'moor', 'morgue', 'mosque indoor', 
            'mosque outdoor', 'motel', 'mountain', 'mountain path', 'mountain road', 'mountain snowy', 'movie theater indoor', 'movie theater outdoor', 
            'museum indoor', 'museum outdoor', 'music store', 'music studio', 'natural history museum', 'naval base', 'newsroom', 'newsstand outdoor', 
            'nightclub', 'nuclear power plant indoor', 'nuclear power plant outdoor', 'nursery', 'nursing home', 'oasis', 'oast house', 
            'observatory indoor', 'observatory outdoor', 'ocean', 'office', 'office building', 'office cubicles', 'oil refinery outdoor', 'oilrig', 
            'operating room', 'optician', 'orchard', 'organ loft exterior', 'ossuary', 'outcropping', 'outhouse outdoor', 'overpass', 'packaging plant', 
            'pagoda', 'palace', 'pantry', 'parade ground', 'park', 'parking garage indoor', 'parking garage outdoor', 'parking lot', 'parlor', 
            'particle accelerator', 'pasture', 'patio', 'pavilion', 'pedestrian overpass outdoor', 'pet shop', 'pharmacy', 'phone booth', 
            'physics laboratory', 'piano store', 'picnic area', 'pier', 'pig farm', 'pilothouse indoor', 'pilothouse outdoor', 'pitchers mound', 
            'pizzeria', 'planetarium indoor', 'planetarium outdoor', 'plantation house', 'playground', 'playroom', 'plaza', 'podium indoor', 
            'podium outdoor', 'pond', 'poolroom establishment', 'poolroom home', 'porch', 'portico', 'power plant indoor', 'power plant outdoor', 
            'print shop', 'priory', 'promenade', 'promenade deck', 'pub indoor', 'pub outdoor', 'pulpit', 'pump room', 'putting green', 'quadrangle', 
            'quay', 'quonset hut outdoor', 'racecourse', 'raceway', 'raft', 'railroad track', 'railway yard', 'rainforest', 'ramp', 'ranch', 
            'ranch house', 'reading room', 'reception', 'recreation room', 'rectory', 'recycling plant indoor', 'recycling plant outdoor', 'repair shop', 
            'residential neighborhood', 'resort', 'restaurant', 'restaurant kitchen', 'restaurant patio', 'restroom indoor', 'restroom outdoor', 
            'revolving door', 'rice paddy', 'riding arena', 'river', 'road cut', 'rock arch', 'rolling mill', 'roof', 'root cellar', 'rope bridge', 
            'roundabout', 'rubble', 'ruin', 'runway', 'sacristy', 'salt plain', 'sand trap', 'sandbar', 'sandbox', 'sauna', 'savanna', 'sawmill', 
            'schoolhouse', 'schoolyard', 'science museum', 'sea cliff', 'seawall', 'server room', 'sewing room', 'shed', 'shipping room', 
            'shipyard outdoor', 'shoe shop', 'shopfront', 'shopping mall indoor', 'shower', 'signal box', 'skatepark', 'ski jump', 'ski lodge', 
            'ski resort', 'ski slope', 'sky', 'skyscraper', 'slum', 'snowfield', 'soccer field', 'spillway', 'squash court', 'stable', 
            'stadium baseball', 'stadium football', 'stadium outdoor', 'stadium soccer', 'stage indoor', 'stage outdoor', 'staircase', 
            'steel mill indoor', 'steel mill outdoor', 'stilt house water', 'stone circle', 'street', 'strip mall', 'strip mine', 'submarine interior', 
            'subway interior', 'subway station corridor', 'subway station platform', 'sun deck', 'supermarket', 'sushi bar', 'swamp', 'swimming hole', 
            'swimming pool indoor', 'swimming pool outdoor', 'synagogue indoor', 'synagogue outdoor', 'tea garden', 'tearoom', 'teashop', 
            'television studio', 'temple east asia', 'temple south asia', 'temple western', 'tennis court indoor', 'tennis court outdoor', 'tent indoor', 
            'tent outdoor', 'terrace farm', 'theater indoor procenium', 'theater indoor round', 'theater indoor seats', 'theater outdoor', 'thriftshop', 
            'throne room', 'ticket booth', 'ticket window outdoor', 'toll plaza', 'tollbooth', 'topiary garden', 'tower', 'town house', 'toyshop', 
            'track indoor', 'track outdoor', 'trading floor', 'trailer park', 'train depot', 'train railway', 'train station outdoor', 
            'train station platform', 'train station station', 'tree farm', 'tree house', 'trench', 'trestle bridge', 'tundra', 'tunnel rail outdoor', 
            'tunnel road outdoor', 'underwater coral reef', 'underwater ice', 'underwater kelp forest', 'underwater ocean deep', 
            'underwater ocean shallow', 'underwater pool', 'underwater wreck', 'utility room', 'valley', 'van interior', 'vegetable garden', 
            'velodrome indoor', 'velodrome outdoor', 'ventilation shaft', 'veranda', 'vestry', 'veterinarians office', 'viaduct', 'videostore', 
            'village', 'vineyard', 'volcano', 'volleyball court outdoor', 'voting booth', 'waiting room', 'warehouse indoor', 'watchtower', 'water mill', 
            'water tower', 'water treatment plant indoor', 'water treatment plant outdoor', 'waterfall block', 'waterfall cascade', 'waterfall cataract', 
            'waterfall fan', 'waterfall plunge', 'watering hole', 'wave', 'weighbridge', 'wet bar', 'wharf', 'wheat field', 'wind farm', 'windmill', 
            'window seat', 'wine cellar barrel storage', 'wine cellar bottle storage', 'winery', 'witness stand', 'woodland', 'workroom', 'workshop', 
            'wrestling ring indoor', 'yard', 'youth hostel', 'zen garden', 'ziggurat', 'zoo']


sun_templates = [
    'a photo of a {}, a type of scene.',
    'a photo of the {}, a type of scene.',
]


awa_classes = ['antelope', 'grizzly bear', 'killer whale', 'beaver', 'dalmatian', 'persian cat', 'horse', 'german shepherd', 'blue whale', 
               'siamese cat', 'skunk', 'mole', 'tiger', 'hippopotamus', 'leopard', 'moose', 'spider monkey', 'humpback whale', 'elephant', 
               'gorilla', 'ox', 'fox', 'sheep', 'seal', 'chimpanzee', 'hamster', 'squirrel', 'rhinoceros', 'rabbit', 'bat', 'giraffe', 'wolf', 
               'chihuahua', 'rat', 'weasel', 'otter', 'buffalo', 'zebra', 'giant panda', 'deer', 'bobcat', 'pig', 'lion', 'mouse', 'polar bear', 
               'collie', 'walrus', 'raccoon', 'cow', 'dolphin']


awa_templates = [
    'a photo of a {}, a type of animals.',
    'a photo of the {}, a type of animals.',
]


flo_classes = ['pink primrose', 'hard-leaved pocket orchid', 'canterbury bells', 'sweet pea', 'english marigold', 'tiger lily', 'moon orchid', 'bird of paradise',
    'monkshood', 'globe thistle', 'snapdragon', "colt's foot", 'king protea', 'spear thistle', 'yellow iris', 'globe flower', 'purple coneflower',
    'peruvian lily', 'balloon flower', 'giant white arum lily', 'fire lily', 'pincushion flower', 'fritillary', 'red ginger', 'grape hyacinth',
    'corn poppy', 'prince of wales feathers', 'stemless gentian', 'artichoke', 'sweet william', 'carnation', 'garden phlox', 'love in the mist',
    'mexican aster', 'alpine sea holly', 'ruby-lipped cattleya', 'cape flower', 'great masterwort', 'siam tulip', 'lenten rose', 'barbeton daisy',
    'daffodil', 'sword lily', 'poinsettia', 'bolero deep blue', 'wallflower', 'marigold', 'buttercup', 'oxeye daisy', 'common dandelion',
    'petunia', 'wild pansy', 'primula', 'sunflower', 'pelargonium', 'bishop of llandaff', 'gaura', 'geranium', 'orange dahlia', 'pink and yellow dahlia',
    'cautleya spicata', 'japanese anemone', 'black-eyed susan', 'silverbush', 'californian poppy', 'osteospermum', 'spring crocus', 'bearded iris',
    'windflower', 'tree poppy', 'gazania', 'azalea', 'water lily', 'rose', 'thorn apple', 'morning glory', 'passion flower', 'lotus', 'toad lily',
    'anthurium', 'frangipani', 'clematis', 'hibiscus', 'columbine', 'desert-rose', 'tree mallow', 'magnolia', 'cyclamen', 'watercress', 'canna lily',
    'hippeastrum', 'bee balm', 'air plant', 'foxglove', 'bougainvillea', 'camellia', 'mallow', 'mexican petunia', 'bromelia', 'blanket flower',
    'trumpet creeper', 'blackberry lily',
]

flo_templates = [
    'a photo of a {}, a type of flower.',
]


country_classes = ['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua and Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola', 'Antarctica',
    'Argentina', 'Austria', 'Australia', 'Aruba', 'Aland Islands', 'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh', 'Belgium',
    'Burkina Faso', 'Bulgaria', 'Bahrain', 'Benin', 'Bermuda', 'Brunei Darussalam', 'Bolivia', 'Bonaire, Saint Eustatius and Saba', 'Brazil',
    'Bahamas', 'Bhutan', 'Botswana', 'Belarus', 'Belize', 'Canada', 'DR Congo', 'Central African Republic', 'Switzerland', "Cote d'Ivoire",
    'Cook Islands', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cabo Verde', 'Curacao', 'Cyprus', 'Czech Republic',
    'Germany', 'Denmark', 'Dominica', 'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Spain', 'Ethiopia', 'Finland', 'Fiji',
    'Falkland Islands', 'Faeroe Islands', 'France', 'Gabon', 'United Kingdom', 'Grenada', 'Georgia', 'French Guiana', 'Guernsey', 'Ghana',
    'Gibraltar', 'Greenland', 'Gambia', 'Guadeloupe', 'Greece', 'South Georgia and South Sandwich Is.', 'Guatemala', 'Guam', 'Guyana', 'Hong Kong',
    'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'Isle of Man', 'India', 'Iraq', 'Iran', 'Iceland',
    'Italy', 'Jersey', 'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'St. Kitts and Nevis', 'North Korea',
    'South Korea', 'Kuwait', 'Cayman Islands', 'Kazakhstan', 'Laos', 'Lebanon', 'St. Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia',
    'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco', 'Monaco', 'Moldova', 'Montenegro', 'Saint-Martin', 'Madagascar', 'Macedonia', 'Mali',
    'Myanmar', 'Mongolia', 'Macau', 'Martinique', 'Mauritania', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia', 'Mozambique',
    'Namibia', 'New Caledonia', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'New Zealand', 'Oman', 'Panama', 'Peru', 'French Polynesia',
    'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'Puerto Rico', 'Palestine', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Reunion', 'Romania',
    'Serbia', 'Russia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'St. Helena', 'Slovenia', 'Svalbard and Jan Mayen Islands',
    'Slovakia', 'Sierra Leone', 'San Marino', 'Senegal', 'Somalia', 'South Sudan', 'El Salvador', 'Sint Maarten', 'Syria', 'Eswatini', 'Togo', 'Thailand',
    'Tajikistan', 'Timor-Leste', 'Turkmenistan', 'Tunisia', 'Tonga', 'Turkey', 'Trinidad and Tobago', 'Taiwan', 'Tanzania', 'Ukraine', 'Uganda', 'United States',
    'Uruguay', 'Uzbekistan', 'Vatican', 'Venezuela', 'British Virgin Islands', 'United States Virgin Islands', 'Vietnam', 'Vanuatu', 'Samoa', 'Kosovo',
    'Yemen', 'South Africa', 'Zambia', 'Zimbabwe',
]

country_templates = [
    'a photo i took in {}.',
    'a photo i took while visiting {}.',
    'a photo from my home country of {}.',
    'a photo from my visit to {}.',
    'a photo showing the country of {}.',
]



stanfordcar_classes = ['AM General Hummer SUV 2000', 'Acura RL Sedan 2012', 'Acura TL Sedan 2012', 'Acura TL Type-S 2008', 'Acura TSX Sedan 2012', 
                      'Acura Integra Type R 2001', 'Acura ZDX Hatchback 2012', 'Aston Martin V8 Vantage Convertible 2012', 
                      'Aston Martin V8 Vantage Coupe 2012', 'Aston Martin Virage Convertible 2012', 'Aston Martin Virage Coupe 2012', 
                      'Audi RS 4 Convertible 2008', 'Audi A5 Coupe 2012', 'Audi TTS Coupe 2012', 'Audi R8 Coupe 2012', 'Audi V8 Sedan 1994', 
                      'Audi 100 Sedan 1994', 'Audi 100 Wagon 1994', 'Audi TT Hatchback 2011', 'Audi S6 Sedan 2011', 'Audi S5 Convertible 2012', 
                      'Audi S5 Coupe 2012', 'Audi S4 Sedan 2012', 'Audi S4 Sedan 2007', 'Audi TT RS Coupe 2012', 'BMW ActiveHybrid 5 Sedan 2012', 
                      'BMW 1 Series Convertible 2012', 'BMW 1 Series Coupe 2012', 'BMW 3 Series Sedan 2012', 'BMW 3 Series Wagon 2012', 
                      'BMW 6 Series Convertible 2007', 'BMW X5 SUV 2007', 'BMW X6 SUV 2012', 'BMW M3 Coupe 2012', 'BMW M5 Sedan 2010', 
                      'BMW M6 Convertible 2010', 'BMW X3 SUV 2012', 'BMW Z4 Convertible 2012', 'Bentley Continental Supersports Conv. Convertible 2012', 
                      'Bentley Arnage Sedan 2009', 'Bentley Mulsanne Sedan 2011', 'Bentley Continental GT Coupe 2012', 'Bentley Continental GT Coupe 2007', 
                      'Bentley Continental Flying Spur Sedan 2007', 'Bugatti Veyron 16.4 Convertible 2009', 'Bugatti Veyron 16.4 Coupe 2009', 
                      'Buick Regal GS 2012', 'Buick Rainier SUV 2007', 'Buick Verano Sedan 2012', 'Buick Enclave SUV 2012', 'Cadillac CTS-V Sedan 2012', 
                      'Cadillac SRX SUV 2012', 'Cadillac Escalade EXT Crew Cab 2007', 'Chevrolet Silverado 1500 Hybrid Crew Cab 2012', 
                      'Chevrolet Corvette Convertible 2012', 'Chevrolet Corvette ZR1 2012', 'Chevrolet Corvette Ron Fellows Edition Z06 2007', 
                      'Chevrolet Traverse SUV 2012', 'Chevrolet Camaro Convertible 2012', 'Chevrolet HHR SS 2010', 'Chevrolet Impala Sedan 2007', 
                      'Chevrolet Tahoe Hybrid SUV 2012', 'Chevrolet Sonic Sedan 2012', 'Chevrolet Express Cargo Van 2007', 
                      'Chevrolet Avalanche Crew Cab 2012', 'Chevrolet Cobalt SS 2010', 'Chevrolet Malibu Hybrid Sedan 2010', 
                      'Chevrolet TrailBlazer SS 2009', 'Chevrolet Silverado 2500HD Regular Cab 2012', 'Chevrolet Silverado 1500 Classic Extended Cab 2007', 
                      'Chevrolet Express Van 2007', 'Chevrolet Monte Carlo Coupe 2007', 'Chevrolet Malibu Sedan 2007', 
                      'Chevrolet Silverado 1500 Extended Cab 2012', 'Chevrolet Silverado 1500 Regular Cab 2012', 'Chrysler Aspen SUV 2009', 
                      'Chrysler Sebring Convertible 2010', 'Chrysler Town and Country Minivan 2012', 'Chrysler 300 SRT-8 2010', 
                      'Chrysler Crossfire Convertible 2008', 'Chrysler PT Cruiser Convertible 2008', 'Daewoo Nubira Wagon 2002', 'Dodge Caliber Wagon 2012', 
                      'Dodge Caliber Wagon 2007', 'Dodge Caravan Minivan 1997', 'Dodge Ram Pickup 3500 Crew Cab 2010', 'Dodge Ram Pickup 3500 Quad Cab 2009', 
                      'Dodge Sprinter Cargo Van 2009', 'Dodge Journey SUV 2012', 'Dodge Dakota Crew Cab 2010', 'Dodge Dakota Club Cab 2007', 
                      'Dodge Magnum Wagon 2008', 'Dodge Challenger SRT8 2011', 'Dodge Durango SUV 2012', 'Dodge Durango SUV 2007', 
                      'Dodge Charger Sedan 2012', 'Dodge Charger SRT-8 2009', 'Eagle Talon Hatchback 1998', 'FIAT 500 Abarth 2012', 
                      'FIAT 500 Convertible 2012', 'Ferrari FF Coupe 2012', 'Ferrari California Convertible 2012', 'Ferrari 458 Italia Convertible 2012', 
                      'Ferrari 458 Italia Coupe 2012', 'Fisker Karma Sedan 2012', 'Ford F-450 Super Duty Crew Cab 2012', 'Ford Mustang Convertible 2007', 
                      'Ford Freestar Minivan 2007', 'Ford Expedition EL SUV 2009', 'Ford Edge SUV 2012', 'Ford Ranger SuperCab 2011', 'Ford GT Coupe 2006', 
                      'Ford F-150 Regular Cab 2012', 'Ford F-150 Regular Cab 2007', 'Ford Focus Sedan 2007', 'Ford E-Series Wagon Van 2012', 
                      'Ford Fiesta Sedan 2012', 'GMC Terrain SUV 2012', 'GMC Savana Van 2012', 'GMC Yukon Hybrid SUV 2012', 'GMC Acadia SUV 2012', 
                      'GMC Canyon Extended Cab 2012', 'Geo Metro Convertible 1993', 'HUMMER H3T Crew Cab 2010', 'HUMMER H2 SUT Crew Cab 2009', 
                      'Honda Odyssey Minivan 2012', 'Honda Odyssey Minivan 2007', 'Honda Accord Coupe 2012', 'Honda Accord Sedan 2012', 
                      'Hyundai Veloster Hatchback 2012', 'Hyundai Santa Fe SUV 2012', 'Hyundai Tucson SUV 2012', 'Hyundai Veracruz SUV 2012', 
                      'Hyundai Sonata Hybrid Sedan 2012', 'Hyundai Elantra Sedan 2007', 'Hyundai Accent Sedan 2012', 'Hyundai Genesis Sedan 2012', 
                      'Hyundai Sonata Sedan 2012', 'Hyundai Elantra Touring Hatchback 2012', 'Hyundai Azera Sedan 2012', 'Infiniti G Coupe IPL 2012', 
                      'Infiniti QX56 SUV 2011', 'Isuzu Ascender SUV 2008', 'Jaguar XK XKR 2012', 'Jeep Patriot SUV 2012', 'Jeep Wrangler SUV 2012', 
                      'Jeep Liberty SUV 2012', 'Jeep Grand Cherokee SUV 2012', 'Jeep Compass SUV 2012', 'Lamborghini Reventon Coupe 2008', 
                      'Lamborghini Aventador Coupe 2012', 'Lamborghini Gallardo LP 570-4 Superleggera 2012', 'Lamborghini Diablo Coupe 2001', 
                      'Land Rover Range Rover SUV 2012', 'Land Rover LR2 SUV 2012', 'Lincoln Town Car Sedan 2011', 'MINI Cooper Roadster Convertible 2012', 
                      'Maybach Landaulet Convertible 2012', 'Mazda Tribute SUV 2011', 'McLaren MP4-12C Coupe 2012', 
                      'Mercedes-Benz 300-Class Convertible 1993', 'Mercedes-Benz C-Class Sedan 2012', 'Mercedes-Benz SL-Class Coupe 2009', 
                      'Mercedes-Benz E-Class Sedan 2012', 'Mercedes-Benz S-Class Sedan 2012', 'Mercedes-Benz Sprinter Van 2012', 
                      'Mitsubishi Lancer Sedan 2012', 'Nissan Leaf Hatchback 2012', 'Nissan NV Passenger Van 2012', 'Nissan Juke Hatchback 2012', 
                      'Nissan 240SX Coupe 1998', 'Plymouth Neon Coupe 1999', 'Porsche Panamera Sedan 2012', 'Ram C/V Cargo Van Minivan 2012', 
                      'Rolls-Royce Phantom Drophead Coupe Convertible 2012', 'Rolls-Royce Ghost Sedan 2012', 'Rolls-Royce Phantom Sedan 2012', 
                      'Scion xD Hatchback 2012', 'Spyker C8 Convertible 2009', 'Spyker C8 Coupe 2009', 'Suzuki Aerio Sedan 2007', 
                      'Suzuki Kizashi Sedan 2012', 'Suzuki SX4 Hatchback 2012', 'Suzuki SX4 Sedan 2012', 'Tesla Model S Sedan 2012', 
                      'Toyota Sequoia SUV 2012', 'Toyota Camry Sedan 2012', 'Toyota Corolla Sedan 2012', 'Toyota 4Runner SUV 2012', 
                      'Volkswagen Golf Hatchback 2012', 'Volkswagen Golf Hatchback 1991', 'Volkswagen Beetle Hatchback 2012', 'Volvo C30 Hatchback 2012', 
                      'Volvo 240 Sedan 1993', 'Volvo XC90 SUV 2007', 'smart fortwo Convertible 2012']



stanfordcar_templates = [
    'a photo of a {}.',
    'a photo of the {}.',
    'a photo of my {}.',
    'i love my {}!',
    'a photo of my dirty {}.',
    'a photo of my clean {}.',
    'a photo of my new {}.',
    'a photo of my old {}.',
]



eurosat_classes = ['forest', 'permanent crop land', 'residential buildings or homes or apartments', 'river', 'pasture land', 'lake or sea',
    'brushland or shrubland', 'annual crop land', 'industrial buildings or commercial buildings', 'highway or road',
]



eurosat_templates = [
    'a centered satellite photo of {}.',
    'a centered satellite photo of a {}.',
    'a centered satellite photo of the {}.',
]



dtd_classes = ['woven', 'grid', 'pleated', 'flecked', 'lacelike', 'matted', 'interlaced', 'swirly', 'bumpy', 'smeared', 'dotted', 'crosshatched', 
               'knitted', 'paisley', 'braided', 'crystalline', 'lined', 'pitted', 'polka-dotted', 'chequered', 'spiralled', 'grooved', 'stained', 
               'frilly', 'fibrous', 'porous', 'stratified', 'wrinkled', 'waffled', 'meshed', 'scaly', 'veined', 'banded', 'blotchy', 'potholed', 
               'sprinkled', 'honeycombed', 'bubbly', 'cobwebbed', 'cracked', 'freckled', 'perforated', 'gauzy', 'zigzagged', 'studded', 'striped', 
               'marbled']


dtd_templates = [
    'a photo of a {} texture.',
    'a photo of a {} pattern.',
    'a photo of a {} thing.',
    'a photo of a {} object.',
    'a photo of the {} texture.',
    'a photo of the {} pattern.',
    'a photo of the {} thing.',
    'a photo of the {} object.',
]




ucf_classes = ['Boxing Punching Bag', 'Military Parade', 'Cutting In Kitchen', 'Rafting', 'Long Jump', 'Hammering', 'Mopping Floor', 'Mixing', 
               'Frisbee Catch', 'Juggling Balls', 'Javelin Throw', 'Kayaking', 'Punch', 'Handstand Walking', 'Soccer Penalty', 'Blow Dry Hair', 
               'Cliff Diving', 'Pole Vault', 'Writing On Board', 'Table Tennis Shot', 'Volleyball Spiking', 'Parallel Bars', 'Billiards', 'Biking', 
               'Sky Diving', 'High Jump', 'Playing Daf', 'Trampoline Jumping', 'Uneven Bars', 'Baseball Pitch', 'Clean And Jerk', 'Rope Climbing', 
               'Hula Hoop', 'Rowing', 'Playing Tabla', 'Soccer Juggling', 'Push Ups', 'Playing Guitar', 'Ice Dancing', 'Playing Flute', 'Head Massage', 
               'Blowing Candles', 'Archery', 'Surfing', 'Playing Sitar', 'Body Weight Squats', 'Cricket Shot', 'Baby Crawling', 'Still Rings', 
               'Wall Pushups', 'Typing', 'Horse Riding', 'Band Marching', 'Tennis Swing', 'Basketball', 'Front Crawl', 'Rock Climbing Indoor', 
               'Apply Lipstick', 'Nunchucks', 'Pommel Horse', 'Basketball Dunk', 'Bench Press', 'Cricket Bowling', 'Drumming', 'Golf Swing', 
               'Skate Boarding', 'Horse Race', 'Diving', 'Sumo Wrestling', 'Haircut', 'Skijet', 'Bowling', 'Boxing Speed Bag', 'Balance Beam', 
               'Tai Chi', 'Yo Yo', 'Pull Ups', 'Fencing', 'Throw Discus', 'Salsa Spin', 'Pizza Tossing', 'Jump Rope', 'Skiing', 'Hammer Throw', 
               'Field Hockey Penalty', 'Playing Cello', 'Floor Gymnastics', 'Apply Eye Makeup', 'Shaving Beard', 'Shotput', 'Jumping Jack', 
               'Playing Piano', 'Swing', 'Walking With Dog', 'Knitting', 'Breast Stroke', 'Brushing Teeth', 'Lunges', 'Playing Dhol', 
               'Handstand Pushups', 'Playing Violin']


ucf_templates = [
    'a photo of a person {}.',
    'a video of a person {}.',
    'a example of a person {}.',
    'a demonstration of a person {}.',
    'a photo of the person {}.',
    'a video of the person {}.',
    'a example of the person {}.',
    'a demonstration of the person {}.',
    'a photo of a person using {}.',
    'a video of a person using {}.',
    'a example of a person using {}.',
    'a demonstration of a person using {}.',
    'a photo of the person using {}.',
    'a video of the person using {}.',
    'a example of the person using {}.',
    'a demonstration of the person using {}.',
    'a photo of a person doing {}.',
    'a video of a person doing {}.',
    'a example of a person doing {}.',
    'a demonstration of a person doing {}.',
    'a photo of the person doing {}.',
    'a video of the person doing {}.',
    'a example of the person doing {}.',
    'a demonstration of the person doing {}.',
    'a photo of a person during {}.',
    'a video of a person during {}.',
    'a example of a person during {}.',
    'a demonstration of a person during {}.',
    'a photo of the person during {}.',
    'a video of the person during {}.',
    'a example of the person during {}.',
    'a demonstration of the person during {}.',
    'a photo of a person performing {}.',
    'a video of a person performing {}.',
    'a example of a person performing {}.',
    'a demonstration of a person performing {}.',
    'a photo of the person performing {}.',
    'a video of the person performing {}.',
    'a example of the person performing {}.',
    'a demonstration of the person performing {}.',
    'a photo of a person practicing {}.',
    'a video of a person practicing {}.',
    'a example of a person practicing {}.',
    'a demonstration of a person practicing {}.',
    'a photo of the person practicing {}.',
    'a video of the person practicing {}.',
    'a example of the person practicing {}.',
    'a demonstration of the person practicing {}.',
]


caltech_classes = ['helicopter', 'panda', 'wild cat', 'car side', 'ant', 'strawberry', 'soccer ball', 'saxophone', 'scorpion', 'wrench', 'emu', 'cannon', 
                   'minaret', 'brontosaurus', 'ferry', 'butterfly', 'garfield', 'hawksbill', 'ceiling fan', 'platypus', 'BACKGROUND Google', 'Faces easy', 
                   'kangaroo', 'flamingo head', 'llama', 'bass', 'lobster', 'crocodile head', 'gramophone', 'hedgehog', 'lamp', 'crocodile', 'accordion', 
                   'mandolin', 'rhino', 'Leopards', 'stop sign', 'lotus', 'metronome', 'crayfish', 'laptop', 'inline skate', 'headphone', 'okapi', 'crab', 
                   'Faces', 'elephant', 'menorah', 'flamingo', 'octopus', 'watch', 'trilobite', 'sunflower', 'pigeon', 'dragonfly', 'grand piano', 'stapler', 
                   'euphonium', 'cougar body', 'mayfly', 'dolphin', 'ibis', 'pizza', 'cougar face', 'schooner', 'sea horse', 'buddha', 'Motorbikes', 
                   'pyramid', 'starfish', 'cellphone', 'water lilly', 'wheelchair', 'gerenuk', 'snoopy', 'electric guitar', 'dalmatian', 'windsor chair', 
                   'scissors', 'bonsai', 'yin yang', 'dollar bill', 'ketch', 'rooster', 'pagoda', 'nautilus', 'chandelier', 'anchor', 'umbrella', 'camera', 
                   'cup', 'joshua tree', 'beaver', 'ewer', 'chair', 'stegosaurus', 'barrel', 'revolver', 'tick', 'binocular', 'airplanes', 'brain'
]


caltech_templates = ['a photo of a {}.',
    'a painting of a {}.',
    'a plastic {}.',
    'a sculpture of a {}.',
    'a sketch of a {}.',
    'a tattoo of a {}.',
    'a toy {}.',
    'a rendition of a {}.',
    'a embroidered {}.',
    'a cartoon {}.',
    'a {} in a video game.',
    'a plushie {}.',
    'a origami {}.',
    'art of a {}.',
    'graffiti of a {}.',
    'a drawing of a {}.',
    'a doodle of a {}.',
    'a photo of the {}.',
    'a painting of the {}.',
    'the plastic {}.',
    'a sculpture of the {}.',
    'a sketch of the {}.',
    'a tattoo of the {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'the embroidered {}.',
    'the cartoon {}.',
    'the {} in a video game.',
    'the plushie {}.',
    'the origami {}.',
    'art of the {}.',
    'graffiti of the {}.',
    'a drawing of the {}.',
    'a doodle of the {}.',
]




oxfordpet_classes = ['Ragdoll', 'British Shorthair', 'german shorthaired', 'miniature pinscher', 'keeshond', 'Sphynx', 'great pyrenees', 'american bulldog',
                     'chihuahua', 'Bengal', 'havanese', 'samoyed', 'Siamese', 'english setter', 'pomeranian', 'Bombay', 'pug', 'Persian', 
                     'english cocker spaniel', 'staffordshire bull terrier', 'beagle', 'scottish terrier', 'Russian Blue', 'basset hound', 'shiba inu', 
                     'Abyssinian', 'yorkshire terrier', 'Birman', 'wheaten terrier', 'saint bernard', 'american pit bull terrier', 'japanese chin', 
                     'Maine Coon', 'Egyptian Mau', 'leonberger', 'newfoundland', 'boxer'

]
    

oxfordpet_templates = [
    'a photo of a {}, a type of pet.',
]



food_classes = ['tiramisu', 'beignets', 'cup cakes', 'fish and chips', 'pancakes', 'ceviche', 'carrot cake', 'strawberry shortcake', 'bibimbap', 
                'pulled pork sandwich', 'mussels', 'steak', 'fried rice', 'miso soup', 'shrimp and grits', 'croque madame', 'omelette', 'filet mignon', 
                'spaghetti carbonara', 'falafel', 'eggs benedict', 'poutine', 'churros', 'scallops', 'greek salad', 'onion rings', 'seaweed salad', 
                'gnocchi', 'tuna tartare', 'beef carpaccio', 'macaroni and cheese', 'cannoli', 'donuts', 'ravioli', 'fried calamari', 'pho', 'crab cakes', 
                'ramen', 'oysters', 'gyoza', 'bread pudding', 'hot and sour soup', 'hot dog', 'garlic bread', 'chocolate cake', 'french fries', 
                'dumplings', 'samosa', 'baklava', 'macarons', 'chicken curry', 'tacos', 'ice cream', 'paella', 'panna cotta', 'caprese salad', 
                'huevos rancheros', 'spring rolls', 'prime rib', 'pad thai', 'french toast', 'escargots', 'creme brulee', 'guacamole', 'clam chowder', 
                'edamame', 'waffles', 'takoyaki', 'spaghetti bolognese', 'pizza', 'foie gras', 'chicken quesadilla', 'lasagna', 'cheese plate', 
                'cheesecake', 'grilled cheese sandwich', 'sushi', 'french onion soup', 'breakfast burrito', 'lobster roll sandwich', 'beet salad', 
                'lobster bisque', 'club sandwich', 'sashimi', 'beef tartare', 'grilled salmon', 'frozen yogurt', 'chicken wings', 'pork chop', 
                'chocolate mousse', 'red velvet cake', 'bruschetta', 'nachos', 'hamburger', 'risotto', 'apple pie', 'deviled eggs', 'caesar salad', 
                'baby back ribs', 'hummus', 'peking duck'
]
    

food_templates = [
    'a photo of {}, a type of food.',
]



TEMPLATE = {
    # 'imagenet' : imagenet_templates,
    'fgvc-aircraft': fgvc_aircraft_templates,
    'cub_200': cub_templates,
    'sun': sun_templates,
    'awa': awa_templates,
    'flo': flo_templates,
    'country': country_templates,
    'stanfordcar': stanfordcar_templates,
    'eurosat': eurosat_templates,
    'dtd': dtd_templates,
    'ucf': ucf_templates,
    'caltech': caltech_templates,
    'oxfordpet': oxfordpet_templates,
    'food': food_templates,

}


CLASS_NAME = {
    # 'imagenet' : imagenet_classes,
    'fgvc-aircraft': fgvc_aircraft_classes,
    'cub_200': cub_classes,
    'sun': sun_classes,
    'awa': awa_classes,
    'flo': flo_classes,
    'country': country_classes,
    'stanfordcar': stanfordcar_classes,
    'eurosat': eurosat_classes,
    'dtd': dtd_classes,
    'ucf': ucf_classes,
    'caltech': caltech_classes,
    'oxfordpet': oxfordpet_classes,
    'food': food_classes,

}